version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "14:00"
      timezone: America/Phoenix
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "14:30"
      timezone: America/Phoenix
    open-pull-requests-limit: 5
